// Builds src/ui/icons.svg (symbol sprite) + src/ui/icons.js (JS module wrapper)
// from lucide-static + the custom symbols below. Run: node scripts/build-icons.js
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const lucideDir = join(root, 'node_modules', 'lucide-static', 'icons');

// Curated set for the Riffwork family. Add here, rerun, commit both outputs.
const LUCIDE = [
  // transport / edit
  'play', 'pause', 'square', 'skip-back', 'skip-forward', 'repeat', 'shuffle',
  'undo-2', 'redo-2', 'pencil', 'eraser', 'trash-2', 'copy', 'clipboard-paste',
  'save', 'plus', 'minus', 'x', 'check',
  // files / share
  'file', 'folder-open', 'download', 'upload', 'external-link', 'printer',
  'share-2', 'link-2', 'qr-code', 'mail',
  // nav / ui
  'menu', 'search', 'settings', 'sliders-horizontal', 'sliders-vertical',
  'eye', 'eye-off', 'moon', 'sun', 'chevron-up', 'chevron-down', 'chevron-left',
  'chevron-right', 'chevrons-up-down', 'more-horizontal', 'info', 'circle-help',
  'circle-alert', 'keyboard', 'maximize-2', 'grid-3x3', 'list', 'list-checks',
  'lock', 'unlock', 'user', 'users', 'log-in', 'log-out', 'cloud', 'cloud-off',
  'refresh-cw', 'star', 'heart', 'flag', 'bookmark',
  // music
  'music', 'music-2', 'music-4', 'guitar', 'piano', 'drum', 'metronome',
  'audio-lines', 'mic-vocal', 'volume-2', 'volume-x', 'gauge', 'timer',
  'clock', 'activity', 'keyboard-music', 'circle-play',
  // gear / hardware
  'cable', 'plug', 'plug-zap', 'usb', 'bluetooth', 'wifi', 'cpu', 'zap',
  'power', 'wrench', 'layers', 'box', 'speaker', 'circle-dot', 'toggle-right',
  // toolbar verbs (RigWork/Riffwork surfaces)
  'message-circle', 'camera', 'book-open', 'scroll-text', 'ban', 'rotate-ccw',
  'map', 'table', 'scan', 'target', 'arrow-left-right', 'send', 'file-music',
  'pentagon', 'palette', 'move-horizontal', 'arrow-down-to-line',
];

// Custom symbols (24x24, stroke geometry matching Lucide conventions).
const CUSTOM = {
  // 5-pin DIN MIDI jack, face-on
  'midi-din': '<circle cx="12" cy="12" r="9"/><circle cx="12" cy="17" r=".5"/><circle cx="6.5" cy="13.5" r=".5"/><circle cx="17.5" cy="13.5" r=".5"/><circle cx="8" cy="8.5" r=".5"/><circle cx="16" cy="8.5" r=".5"/>',
  // stompbox: enclosure + two knobs + footswitch
  'pedal': '<rect x="6" y="3" width="12" height="18" rx="2"/><circle cx="9.5" cy="7" r="1.2"/><circle cx="14.5" cy="7" r="1.2"/><circle cx="12" cy="16" r="2"/>',
};

const innerOf = (svg) => svg
  .replace(/<!--[\s\S]*?-->/g, '')
  .replace(/^[\s\S]*?<svg[^>]*>/, '')
  .replace(/<\/svg>[\s\S]*$/, '')
  .trim();

const symbols = [];
for (const name of LUCIDE) {
  const svg = readFileSync(join(lucideDir, `${name}.svg`), 'utf8');
  symbols.push(`<symbol id="i-${name}" viewBox="0 0 24 24">${innerOf(svg)}</symbol>`);
}
for (const [name, inner] of Object.entries(CUSTOM)) {
  symbols.push(`<symbol id="i-${name}" viewBox="0 0 24 24">${inner}</symbol>`);
}

const sprite = `<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">${symbols.join('')}</svg>`;
writeFileSync(join(root, 'src', 'ui', 'icons.svg'), sprite + '\n');

const js = `// GENERATED by scripts/build-icons.js — do not edit by hand.
export const ICONS_SPRITE = ${JSON.stringify(sprite)};

export const ICON_NAMES = ${JSON.stringify([...LUCIDE, ...Object.keys(CUSTOM)])};

/** Inject the sprite once into document.body so <use href="#i-name"> resolves. */
export function injectIcons(doc = document) {
  if (doc.getElementById('gp-icon-sprite')) return;
  const div = doc.createElement('div');
  div.id = 'gp-icon-sprite';
  div.innerHTML = ICONS_SPRITE;
  doc.body.prepend(div);
}

/** Markup for one icon. Extra classes via cls (e.g. 'gp-icon--sm'). */
export function icon(name, cls = '') {
  return \`<svg class="gp-icon\${cls ? ' ' + cls : ''}" aria-hidden="true"><use href="#i-\${name}"/></svg>\`;
}
`;
writeFileSync(join(root, 'src', 'ui', 'icons.js'), js);

console.log(`sprite: ${symbols.length} symbols, ${(sprite.length / 1024).toFixed(1)} KB`);
